# Generated by tools/build_submission.py; do not edit.
# task_key=02_fused_moe chip_key=iluvatar_bi150 builder_version=3
import torch
import torch.nn as nn
import triton
import triton.language as tl
_KS_BAKED_PROFILE = {'variant': 'token_rank_reference', 'config': {'route_num_warps': 1, 'gate_up_num_warps': 4, 'down_num_warps': 4, 'reduce_block': 256, 'reduce_num_warps': 4}, 'schema_version': 1, 'task_key': '02_fused_moe', 'chip_key': 'iluvatar_bi150', 'verified': False}

def get_operator_profile(task_key, chip_key=None):
    if task_key != _KS_BAKED_PROFILE['task_key']:
        raise ValueError(f"artifact profile is for {_KS_BAKED_PROFILE['task_key']}, not {task_key}")
    if chip_key is not None and chip_key != _KS_BAKED_PROFILE['chip_key']:
        raise ValueError(f"artifact profile is for {_KS_BAKED_PROFILE['chip_key']}, not {chip_key}")
    return _KS_BAKED_PROFILE

@triton.jit
def _moe_route_kernel(logits_ptr, ids_ptr, weights_ptr, num_experts: tl.constexpr, TOP_K: tl.constexpr, RENORMALIZE: tl.constexpr, BLOCK_E: tl.constexpr):
    token = tl.program_id(0)
    expert = tl.arange(0, BLOCK_E)
    valid = expert < num_experts
    logits = tl.load(logits_ptr + token * num_experts + expert, mask=valid, other=-float('inf'))
    logits = logits.to(tl.float32)
    scores = tl.exp(logits - tl.max(logits, axis=0))
    scores = scores / tl.sum(tl.where(valid, scores, 0.0), axis=0)
    remaining = tl.where(valid, scores, -float('inf'))
    selected_sum = 0.0
    for rank in range(TOP_K):
        expert_id = tl.argmax(remaining, axis=0)
        weight = tl.max(remaining, axis=0)
        tl.store(ids_ptr + token * TOP_K + rank, expert_id)
        tl.store(weights_ptr + token * TOP_K + rank, weight)
        selected_sum += weight
        remaining = tl.where(expert == expert_id, -float('inf'), remaining)
    rank_offsets = tl.arange(0, TOP_K)
    selected = tl.load(weights_ptr + token * TOP_K + rank_offsets)
    if RENORMALIZE:
        selected /= selected_sum
    tl.store(weights_ptr + token * TOP_K + rank_offsets, selected)

@triton.jit
def _moe_gate_up_kernel(x_ptr, ids_ptr, w1_ptr, act_ptr, hidden_size: tl.constexpr, intermediate_size: tl.constexpr, TOP_K: tl.constexpr, BLOCK_H: tl.constexpr, BLOCK_I: tl.constexpr):
    token = tl.program_id(0)
    rank = tl.program_id(1)
    expert = tl.load(ids_ptr + token * TOP_K + rank)
    h = tl.arange(0, BLOCK_H)
    i = tl.arange(0, BLOCK_I)
    h_mask = h < hidden_size
    i_mask = i < intermediate_size
    x = tl.load(x_ptr + token * hidden_size + h, mask=h_mask, other=0.0).to(tl.float32)
    expert_base = expert * 2 * intermediate_size * hidden_size
    gate_w = tl.load(w1_ptr + expert_base + i[:, None] * hidden_size + h[None, :], mask=i_mask[:, None] & h_mask[None, :], other=0.0).to(tl.float16).to(tl.float32)
    up_w = tl.load(w1_ptr + expert_base + (intermediate_size + i[:, None]) * hidden_size + h[None, :], mask=i_mask[:, None] & h_mask[None, :], other=0.0).to(tl.float16).to(tl.float32)
    gate = tl.sum(gate_w * x[None, :], axis=1)
    up = tl.sum(up_w * x[None, :], axis=1)
    act = gate * tl.sigmoid(gate) * up
    tl.store(act_ptr + (token * TOP_K + rank) * intermediate_size + i, act.to(tl.float16), mask=i_mask)

@triton.jit
def _moe_down_kernel(act_ptr, ids_ptr, route_weights_ptr, w2_ptr, contribution_ptr, hidden_size: tl.constexpr, intermediate_size: tl.constexpr, TOP_K: tl.constexpr, BLOCK_H: tl.constexpr, BLOCK_I: tl.constexpr):
    token = tl.program_id(0)
    rank = tl.program_id(1)
    expert = tl.load(ids_ptr + token * TOP_K + rank)
    route_weight = tl.load(route_weights_ptr + token * TOP_K + rank).to(tl.float32)
    h = tl.arange(0, BLOCK_H)
    i = tl.arange(0, BLOCK_I)
    h_mask = h < hidden_size
    i_mask = i < intermediate_size
    act = tl.load(act_ptr + (token * TOP_K + rank) * intermediate_size + i, mask=i_mask, other=0.0).to(tl.float32)
    expert_base = expert * hidden_size * intermediate_size
    w2 = tl.load(w2_ptr + expert_base + h[:, None] * intermediate_size + i[None, :], mask=h_mask[:, None] & i_mask[None, :], other=0.0).to(tl.float16).to(tl.float32)
    down = tl.sum(w2 * act[None, :], axis=1) * route_weight
    tl.store(contribution_ptr + (token * TOP_K + rank) * hidden_size + h, down.to(tl.float16), mask=h_mask)

@triton.jit
def _moe_reduce_kernel(contribution_ptr, out_ptr, total: tl.constexpr, hidden_size: tl.constexpr, TOP_K: tl.constexpr, BLOCK: tl.constexpr):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    valid = offsets < total
    token = offsets // hidden_size
    hidden = offsets % hidden_size
    result = tl.zeros((BLOCK,), tl.float32)
    for rank in range(TOP_K):
        value = tl.load(contribution_ptr + (token * TOP_K + rank) * hidden_size + hidden, mask=valid, other=0.0).to(tl.float32)
        result += value
    tl.store(out_ptr + offsets, result, mask=valid)

class Model(nn.Module):

    def __init__(self, num_experts: int, top_k: int, hidden_size: int, intermediate_size: int, renormalize: bool=True):
        super().__init__()
        self.num_experts = num_experts
        self.top_k = top_k
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.renormalize = renormalize
        self.w1 = nn.Parameter(torch.empty(num_experts, 2 * intermediate_size, hidden_size))
        self.w2 = nn.Parameter(torch.empty(num_experts, hidden_size, intermediate_size))
        nn.init.normal_(self.w1, std=0.02)
        nn.init.normal_(self.w2, std=0.02)
        profile = get_operator_profile('02_fused_moe')
        if profile['variant'] != 'token_rank_reference':
            raise ValueError(f"unsupported FusedMoE variant: {profile['variant']}")
        self._ks_config = profile['config']

    def forward(self, hidden_states: torch.Tensor, router_logits: torch.Tensor):
        num_tokens = hidden_states.shape[0]
        ids = torch.empty((num_tokens, self.top_k), device=hidden_states.device, dtype=torch.int32)
        route_weights = torch.empty((num_tokens, self.top_k), device=hidden_states.device, dtype=hidden_states.dtype)
        block_e = triton.next_power_of_2(self.num_experts)
        _moe_route_kernel[num_tokens,](router_logits, ids, route_weights, self.num_experts, TOP_K=self.top_k, RENORMALIZE=self.renormalize, BLOCK_E=block_e, num_warps=int(self._ks_config['route_num_warps']))
        act = torch.empty((num_tokens, self.top_k, self.intermediate_size), device=hidden_states.device, dtype=hidden_states.dtype)
        block_h = triton.next_power_of_2(self.hidden_size)
        block_i = triton.next_power_of_2(self.intermediate_size)
        _moe_gate_up_kernel[num_tokens, self.top_k](hidden_states, ids, self.w1, act, self.hidden_size, self.intermediate_size, TOP_K=self.top_k, BLOCK_H=block_h, BLOCK_I=block_i, num_warps=int(self._ks_config['gate_up_num_warps']))
        contributions = torch.empty((num_tokens, self.top_k, self.hidden_size), device=hidden_states.device, dtype=hidden_states.dtype)
        _moe_down_kernel[num_tokens, self.top_k](act, ids, route_weights, self.w2, contributions, self.hidden_size, self.intermediate_size, TOP_K=self.top_k, BLOCK_H=block_h, BLOCK_I=block_i, num_warps=int(self._ks_config['down_num_warps']))
        out = torch.empty_like(hidden_states)
        total = out.numel()
        block = int(self._ks_config['reduce_block'])
        _moe_reduce_kernel[triton.cdiv(total, block),](contributions, out, total, self.hidden_size, TOP_K=self.top_k, BLOCK=block, num_warps=int(self._ks_config['reduce_num_warps']))
        return out

def get_inputs():
    hidden_states = torch.randn(83, 128, dtype=torch.float16, device='cuda')
    router_logits = torch.randn(83, 8, dtype=torch.float32, device='cuda')
    return [hidden_states, router_logits]

def get_init_inputs():
    return [8, 2, 128, 64]
