# Generated by tools/build_submission.py; do not edit.
# task_key=01_grouped_topk chip_key=hygon_bw1000 builder_version=5
import torch
import torch.nn as nn
import triton
import triton.language as tl
_KS_BAKED_PROFILE = {'variant': 'vector_reduce', 'config': {'num_warps': 8}, 'fallback_variants': [{'variant': 'manual_stable', 'config': {'num_warps': 4}}], 'schema_version': 1, 'task_key': '01_grouped_topk', 'chip_key': 'hygon_bw1000', 'verified': False}

@triton.jit
def _grouped_topk_kernel(logits_ptr, weights_ptr, ids_ptr, num_experts: tl.constexpr, experts_per_group: tl.constexpr, num_groups: tl.constexpr, TOPK: tl.constexpr, TOPK_GROUPS: tl.constexpr, SOFTMAX: tl.constexpr, RENORMALIZE: tl.constexpr, ROUTED_SCALE: tl.constexpr, BLOCK: tl.constexpr):
    token = tl.program_id(0)
    expert = tl.arange(0, BLOCK)
    mask = expert < num_experts
    logits = tl.load(logits_ptr + token * num_experts + expert, mask=mask, other=-float('inf'))
    logits = logits.to(tl.float32)
    if SOFTMAX:
        shifted = logits - tl.max(logits, axis=0)
        scores = tl.exp(shifted)
        scores = scores / tl.sum(tl.where(mask, scores, 0.0), axis=0)
    else:
        scores = tl.sigmoid(logits)
    grouped = tl.reshape(scores, (num_groups, experts_per_group))
    group_scores = tl.max(grouped, axis=1)
    group_offsets = tl.arange(0, num_groups)
    eligible = tl.zeros((BLOCK,), tl.int1)
    remaining_groups = group_scores
    for _ in range(TOPK_GROUPS):
        group_id = tl.argmax(remaining_groups, axis=0)
        eligible = eligible | (expert // experts_per_group == group_id)
        remaining_groups = tl.where(group_offsets == group_id, -float('inf'), remaining_groups)
    candidates = tl.where(mask & eligible, scores, -float('inf'))
    weight_sum = 0.0
    for k in range(TOPK):
        expert_id = tl.argmax(candidates, axis=0)
        weight = tl.max(candidates, axis=0)
        tl.store(weights_ptr + token * TOPK + k, weight)
        tl.store(ids_ptr + token * TOPK + k, expert_id)
        weight_sum += weight
        candidates = tl.where(expert == expert_id, -float('inf'), candidates)
    out_k = tl.arange(0, TOPK)
    selected = tl.load(weights_ptr + token * TOPK + out_k)
    if RENORMALIZE:
        selected = selected / weight_sum
    selected *= ROUTED_SCALE
    tl.store(weights_ptr + token * TOPK + out_k, selected)

@triton.jit
def _grouped_topk_register_kernel(logits_ptr, weights_ptr, ids_ptr, num_experts: tl.constexpr, experts_per_group: tl.constexpr, num_groups: tl.constexpr, TOPK: tl.constexpr, TOPK_GROUPS: tl.constexpr, SOFTMAX: tl.constexpr, RENORMALIZE: tl.constexpr, ROUTED_SCALE: tl.constexpr, BLOCK: tl.constexpr):
    """Grouped top-k with register-resident selected weights.

    The selection order and arithmetic intentionally match
    ``_grouped_topk_kernel``.  Only the temporary selected weights change
    storage: the eight values are accumulated in a tiny register vector and
    written once after renormalization, avoiding a global write/read pair for
    every rank.
    """
    token = tl.program_id(0)
    expert = tl.arange(0, BLOCK)
    mask = expert < num_experts
    logits = tl.load(logits_ptr + token * num_experts + expert, mask=mask, other=-float('inf')).to(tl.float32)
    if SOFTMAX:
        shifted = logits - tl.max(logits, axis=0)
        scores = tl.exp(shifted)
        scores = scores / tl.sum(tl.where(mask, scores, 0.0), axis=0)
    else:
        scores = tl.sigmoid(logits)
    grouped = tl.reshape(scores, (num_groups, experts_per_group))
    group_scores = tl.max(grouped, axis=1)
    group_offsets = tl.arange(0, num_groups)
    eligible = tl.zeros((BLOCK,), tl.int1)
    remaining_groups = group_scores
    for _ in range(TOPK_GROUPS):
        group_id = tl.argmax(remaining_groups, axis=0)
        eligible = eligible | (expert // experts_per_group == group_id)
        remaining_groups = tl.where(group_offsets == group_id, -float('inf'), remaining_groups)
    candidates = tl.where(mask & eligible, scores, -float('inf'))
    selected_weights = tl.zeros((TOPK,), tl.float32)
    weight_sum = 0.0
    rank_offsets = tl.arange(0, TOPK)
    for rank in range(TOPK):
        expert_id = tl.argmax(candidates, axis=0)
        weight = tl.max(candidates, axis=0)
        selected_weights = tl.where(rank_offsets == rank, weight, selected_weights)
        tl.store(ids_ptr + token * TOPK + rank, expert_id)
        weight_sum += weight
        candidates = tl.where(expert == expert_id, -float('inf'), candidates)
    if RENORMALIZE:
        selected_weights = selected_weights / weight_sum
    selected_weights *= ROUTED_SCALE
    tl.store(weights_ptr + token * TOPK + rank_offsets, selected_weights)

@triton.jit
def _grouped_topk_unrolled8_kernel(logits_ptr, weights_ptr, ids_ptr, num_experts: tl.constexpr, experts_per_group: tl.constexpr, num_groups: tl.constexpr, TOPK: tl.constexpr, TOPK_GROUPS: tl.constexpr, SOFTMAX: tl.constexpr, RENORMALIZE: tl.constexpr, ROUTED_SCALE: tl.constexpr, BLOCK: tl.constexpr):
    """TOPK=8 selection with scalar weight lifetimes.

    The official case uses eight ranks.  The previous vector path writes all
    eight raw weights, reloads them, then writes the normalized vector.  This
    specialization preserves each ``tl.argmax``/``tl.max`` in the same order
    but keeps the eight scalar weights live until the final normalized stores.
    No framework operation is introduced; all routing work remains in this
    Triton program.
    """
    token = tl.program_id(0)
    expert = tl.arange(0, BLOCK)
    mask = expert < num_experts
    logits = tl.load(logits_ptr + token * num_experts + expert, mask=mask, other=-float('inf')).to(tl.float32)
    if SOFTMAX:
        shifted = logits - tl.max(logits, axis=0)
        scores = tl.exp(shifted)
        scores = scores / tl.sum(tl.where(mask, scores, 0.0), axis=0)
    else:
        scores = tl.sigmoid(logits)
    grouped = tl.reshape(scores, (num_groups, experts_per_group))
    group_scores = tl.max(grouped, axis=1)
    group_offsets = tl.arange(0, num_groups)
    eligible = tl.zeros((BLOCK,), tl.int1)
    remaining_groups = group_scores
    for _ in range(TOPK_GROUPS):
        group_id = tl.argmax(remaining_groups, axis=0)
        eligible = eligible | (expert // experts_per_group == group_id)
        remaining_groups = tl.where(group_offsets == group_id, -float('inf'), remaining_groups)
    candidates = tl.where(mask & eligible, scores, -float('inf'))
    expert0 = tl.argmax(candidates, axis=0)
    weight0 = tl.max(candidates, axis=0)
    candidates = tl.where(expert == expert0, -float('inf'), candidates)
    expert1 = tl.argmax(candidates, axis=0)
    weight1 = tl.max(candidates, axis=0)
    candidates = tl.where(expert == expert1, -float('inf'), candidates)
    expert2 = tl.argmax(candidates, axis=0)
    weight2 = tl.max(candidates, axis=0)
    candidates = tl.where(expert == expert2, -float('inf'), candidates)
    expert3 = tl.argmax(candidates, axis=0)
    weight3 = tl.max(candidates, axis=0)
    candidates = tl.where(expert == expert3, -float('inf'), candidates)
    expert4 = tl.argmax(candidates, axis=0)
    weight4 = tl.max(candidates, axis=0)
    candidates = tl.where(expert == expert4, -float('inf'), candidates)
    expert5 = tl.argmax(candidates, axis=0)
    weight5 = tl.max(candidates, axis=0)
    candidates = tl.where(expert == expert5, -float('inf'), candidates)
    expert6 = tl.argmax(candidates, axis=0)
    weight6 = tl.max(candidates, axis=0)
    candidates = tl.where(expert == expert6, -float('inf'), candidates)
    expert7 = tl.argmax(candidates, axis=0)
    weight7 = tl.max(candidates, axis=0)
    weight_sum = 0.0
    weight_sum += weight0
    weight_sum += weight1
    weight_sum += weight2
    weight_sum += weight3
    weight_sum += weight4
    weight_sum += weight5
    weight_sum += weight6
    weight_sum += weight7
    if RENORMALIZE:
        weight0 = weight0 / weight_sum
        weight1 = weight1 / weight_sum
        weight2 = weight2 / weight_sum
        weight3 = weight3 / weight_sum
        weight4 = weight4 / weight_sum
        weight5 = weight5 / weight_sum
        weight6 = weight6 / weight_sum
        weight7 = weight7 / weight_sum
    weight0 *= ROUTED_SCALE
    weight1 *= ROUTED_SCALE
    weight2 *= ROUTED_SCALE
    weight3 *= ROUTED_SCALE
    weight4 *= ROUTED_SCALE
    weight5 *= ROUTED_SCALE
    weight6 *= ROUTED_SCALE
    weight7 *= ROUTED_SCALE
    base = token * TOPK
    tl.store(weights_ptr + base + 0, weight0)
    tl.store(weights_ptr + base + 1, weight1)
    tl.store(weights_ptr + base + 2, weight2)
    tl.store(weights_ptr + base + 3, weight3)
    tl.store(weights_ptr + base + 4, weight4)
    tl.store(weights_ptr + base + 5, weight5)
    tl.store(weights_ptr + base + 6, weight6)
    tl.store(weights_ptr + base + 7, weight7)
    tl.store(ids_ptr + base + 0, expert0)
    tl.store(ids_ptr + base + 1, expert1)
    tl.store(ids_ptr + base + 2, expert2)
    tl.store(ids_ptr + base + 3, expert3)
    tl.store(ids_ptr + base + 4, expert4)
    tl.store(ids_ptr + base + 5, expert5)
    tl.store(ids_ptr + base + 6, expert6)
    tl.store(ids_ptr + base + 7, expert7)

@triton.jit
def _grouped_topk_manual_kernel(logits_ptr, weights_ptr, ids_ptr, num_experts: tl.constexpr, experts_per_group: tl.constexpr, num_groups: tl.constexpr, TOPK: tl.constexpr, TOPK_GROUPS: tl.constexpr, SOFTMAX: tl.constexpr, RENORMALIZE: tl.constexpr, ROUTED_SCALE: tl.constexpr, BLOCK: tl.constexpr, GROUP_BLOCK: tl.constexpr):
    """Portable selection path without tl.reshape or tl.argmax.

    Equal scores are resolved toward the lowest group/expert id.  Target runs
    still need to compare that behavior with the vendor's torch.topk tie order.
    """
    token = tl.program_id(0)
    expert = tl.arange(0, BLOCK)
    expert_mask = expert < num_experts
    logits = tl.load(logits_ptr + token * num_experts + expert, mask=expert_mask, other=-float('inf')).to(tl.float32)
    if SOFTMAX:
        shifted = logits - tl.max(logits, axis=0)
        scores = tl.exp(shifted)
        scores = scores / tl.sum(tl.where(expert_mask, scores, 0.0), axis=0)
    else:
        scores = tl.sigmoid(logits)
    group_lane = tl.arange(0, GROUP_BLOCK)
    group_scores = tl.full((GROUP_BLOCK,), -float('inf'), tl.float32)
    for group in range(num_groups):
        in_group = (expert >= group * experts_per_group) & (expert < (group + 1) * experts_per_group)
        score = tl.max(tl.where(expert_mask & in_group, scores, -float('inf')), axis=0)
        group_scores = tl.where(group_lane == group, score, group_scores)
    selected_groups = tl.zeros((GROUP_BLOCK,), tl.int1)
    eligible = tl.zeros((BLOCK,), tl.int1)
    for _ in range(TOPK_GROUPS):
        candidates = tl.where((group_lane < num_groups) & ~selected_groups, group_scores, -float('inf'))
        best_score = tl.max(candidates, axis=0)
        group_id = tl.min(tl.where(candidates == best_score, group_lane, GROUP_BLOCK), axis=0)
        selected_groups = selected_groups | (group_lane == group_id)
        eligible = eligible | (expert // experts_per_group == group_id)
    candidates = tl.where(expert_mask & eligible, scores, -float('inf'))
    weight_sum = 0.0
    for rank in range(TOPK):
        weight = tl.max(candidates, axis=0)
        expert_id = tl.min(tl.where(candidates == weight, expert, BLOCK), axis=0)
        tl.store(weights_ptr + token * TOPK + rank, weight)
        tl.store(ids_ptr + token * TOPK + rank, expert_id)
        weight_sum += weight
        candidates = tl.where(expert == expert_id, -float('inf'), candidates)
    output_rank = tl.arange(0, TOPK)
    selected = tl.load(weights_ptr + token * TOPK + output_rank)
    if RENORMALIZE:
        selected = selected / weight_sum
    selected *= ROUTED_SCALE
    tl.store(weights_ptr + token * TOPK + output_rank, selected)

class Model(nn.Module):

    def __init__(self, topk: int, renormalize: bool, num_expert_group: int, topk_group: int, scoring_func: str='softmax', routed_scaling_factor: float=1.0):
        super().__init__()
        self.topk = topk
        self.renormalize = renormalize
        self.num_expert_group = num_expert_group
        self.topk_group = topk_group
        self.scoring_func = scoring_func
        self.routed_scaling_factor = routed_scaling_factor
        if scoring_func not in {'softmax', 'sigmoid'}:
            raise ValueError(f'Unsupported scoring_func: {scoring_func}')
        profile = _KS_BAKED_PROFILE
        if profile['variant'] not in {'vector_reduce', 'manual_stable', 'register_reduce', 'unrolled_reduce'}:
            raise ValueError(f"unsupported GroupedTopk variant: {profile['variant']}")
        self._ks_variant = profile['variant']
        self._ks_num_warps = int(profile['config']['num_warps'])

    def forward(self, hidden_states: torch.Tensor, gating_output: torch.Tensor):
        num_tokens, num_experts = gating_output.shape
        if hidden_states.shape[0] != num_tokens:
            raise ValueError('hidden_states and gating_output batch sizes must match')
        if self.num_expert_group <= 0 or num_experts % self.num_expert_group != 0:
            raise ValueError('num_experts must be divisible by num_expert_group')
        if not 0 < self.topk <= num_experts:
            raise ValueError('topk must be in the range [1, num_experts]')
        if not 0 < self.topk_group <= self.num_expert_group:
            raise ValueError('topk_group must be in the range [1, num_expert_group]')
        experts_per_group = num_experts // self.num_expert_group
        weights = torch.empty((num_tokens, self.topk), device=gating_output.device, dtype=torch.float32)
        ids = torch.empty((num_tokens, self.topk), device=gating_output.device, dtype=torch.int32)
        block = triton.next_power_of_2(num_experts)
        if self._ks_variant == 'manual_stable':
            kernel = _grouped_topk_manual_kernel
        elif self._ks_variant == 'register_reduce':
            kernel = _grouped_topk_register_kernel
        elif self._ks_variant == 'unrolled_reduce':
            if self.topk != 8:
                raise ValueError('unrolled_reduce requires topk == 8')
            kernel = _grouped_topk_unrolled8_kernel
        else:
            kernel = _grouped_topk_kernel
        launch = dict(TOPK=self.topk, TOPK_GROUPS=self.topk_group, SOFTMAX=self.scoring_func == 'softmax', RENORMALIZE=self.renormalize, ROUTED_SCALE=self.routed_scaling_factor, BLOCK=block, num_warps=self._ks_num_warps)
        if self._ks_variant == 'manual_stable':
            launch['GROUP_BLOCK'] = triton.next_power_of_2(self.num_expert_group)
        kernel[num_tokens,](gating_output, weights, ids, num_experts, experts_per_group, self.num_expert_group, **launch)
        return (weights, ids)

def get_inputs():
    num_tokens, hidden_size, num_experts = (83, 7168, 256)
    hidden_states = torch.randn(num_tokens, hidden_size, dtype=torch.float16)
    gating_output = torch.randn(num_tokens, num_experts, dtype=torch.float32)
    return [hidden_states, gating_output]

def get_init_inputs():
    return [8, True, 8, 4]
