# Generated by tools/build_submission.py; do not edit.
# task_key=07_mhc_post chip_key=enflame_s60 builder_version=5
import torch_gcu
import torch
import torch.nn as nn
import triton
import triton.language as tl
_KS_BAKED_PROFILE = {'variant': 'tiled_hidden', 'config': {'block_hidden': 256, 'block_tokens': 4, 'num_warps': 4}, 'schema_version': 1, 'task_key': '07_mhc_post', 'chip_key': 'enflame_s60', 'verified': False}

@triton.jit
def _mhc_post_kernel(x_ptr, residual_ptr, post_mix_ptr, comb_mix_ptr, out_ptr, hidden_size: tl.constexpr, mhc_mult: tl.constexpr, total: tl.constexpr, BLOCK: tl.constexpr):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < total
    hidden = offsets % hidden_size
    out_mix = offsets // hidden_size % mhc_mult
    token = offsets // (hidden_size * mhc_mult)
    x = tl.load(x_ptr + token * hidden_size + hidden, mask=mask, other=0.0).to(tl.float32)
    post = tl.load(post_mix_ptr + token * mhc_mult + out_mix, mask=mask, other=0.0).to(tl.float32)
    result = x * post
    for in_mix in range(mhc_mult):
        residual = tl.load(residual_ptr + token * mhc_mult * hidden_size + in_mix * hidden_size + hidden, mask=mask, other=0.0).to(tl.float32)
        coefficient = tl.load(comb_mix_ptr + token * mhc_mult * mhc_mult + in_mix * mhc_mult + out_mix, mask=mask, other=0.0).to(tl.float32)
        result += coefficient * residual
    tl.store(out_ptr + offsets, result.to(tl.bfloat16), mask=mask)

@triton.jit
def _mhc_post_tiled_kernel(x_ptr, residual_ptr, post_mix_ptr, comb_mix_ptr, out_ptr, hidden_size: tl.constexpr, mhc_mult: tl.constexpr, token_count, BLOCK_H: tl.constexpr, BLOCK_TOKENS: tl.constexpr):
    """Compute a token tile, output mix and hidden tile per program.

    The post and combination coefficients are scalar for a hidden tile.  This
    grid therefore loads each coefficient once instead of repeating the load
    for every flat output element.  Grouping tokens also keeps Ascend's
    flattened ``coreDim`` below its 65535 launch limit for the reference
    2x4096 input, while retaining the reference's fp32 accumulation and
    bfloat16 output semantics.
    """
    token = tl.program_id(0) * BLOCK_TOKENS + tl.arange(0, BLOCK_TOKENS)
    out_mix = tl.program_id(1)
    hidden_tile = tl.program_id(2)
    hidden = hidden_tile * BLOCK_H + tl.arange(0, BLOCK_H)
    token_mask = token < token_count
    hidden_mask = hidden < hidden_size
    mask = token_mask[:, None] & hidden_mask[None, :]
    x = tl.load(x_ptr + token[:, None] * hidden_size + hidden[None, :], mask=mask, other=0.0).to(tl.float32)
    post = tl.load(post_mix_ptr + token * mhc_mult + out_mix, mask=token_mask, other=0.0).to(tl.float32)[:, None]
    result = x * post
    for in_mix in range(mhc_mult):
        residual = tl.load(residual_ptr + token[:, None] * mhc_mult * hidden_size + in_mix * hidden_size + hidden[None, :], mask=mask, other=0.0).to(tl.float32)
        coefficient = tl.load(comb_mix_ptr + token * mhc_mult * mhc_mult + in_mix * mhc_mult + out_mix, mask=token_mask, other=0.0).to(tl.float32)
        result += coefficient[:, None] * residual
    out_offset = (token[:, None] * mhc_mult + out_mix) * hidden_size + hidden[None, :]
    tl.store(out_ptr + out_offset, result.to(tl.bfloat16), mask=mask)

@triton.jit
def _mhc_post_fused_mix_kernel(x_ptr, residual_ptr, post_mix_ptr, comb_mix_ptr, out_ptr, hidden_size: tl.constexpr, mhc_mult: tl.constexpr, token_count, BLOCK_H: tl.constexpr, BLOCK_TOKENS: tl.constexpr, BLOCK_MIXES: tl.constexpr):
    """Fuse all output mix lanes for one token/hidden tile.

    The reference has four output mix lanes.  The previous tiled kernel
    launched one program per output lane, reloading the same ``x`` and all
    residual lanes four times.  This variant keeps the four output lanes in
    one program, sharing those loads while retaining the reference's fp32
    accumulation and bf16 store.
    """
    token = tl.program_id(0) * BLOCK_TOKENS + tl.arange(0, BLOCK_TOKENS)
    hidden_tile = tl.program_id(1)
    out_mix = tl.arange(0, BLOCK_MIXES)
    hidden = hidden_tile * BLOCK_H + tl.arange(0, BLOCK_H)
    token_mask = token < token_count
    hidden_mask = hidden < hidden_size
    mix_mask = out_mix < mhc_mult
    mask = token_mask[:, None, None] & mix_mask[None, :, None] & hidden_mask[None, None, :]
    x = tl.load(x_ptr + token[:, None] * hidden_size + hidden[None, :], mask=token_mask[:, None] & hidden_mask[None, :], other=0.0).to(tl.float32)
    post = tl.load(post_mix_ptr + token[:, None] * mhc_mult + out_mix[None, :], mask=token_mask[:, None] & mix_mask[None, :], other=0.0).to(tl.float32)
    result = x[:, None, :] * post[:, :, None]
    for in_mix in range(mhc_mult):
        residual = tl.load(residual_ptr + token[:, None] * mhc_mult * hidden_size + in_mix * hidden_size + hidden[None, :], mask=token_mask[:, None] & hidden_mask[None, :], other=0.0).to(tl.float32)
        coefficient = tl.load(comb_mix_ptr + token[:, None] * mhc_mult * mhc_mult + in_mix * mhc_mult + out_mix[None, :], mask=token_mask[:, None] & mix_mask[None, :], other=0.0).to(tl.float32)
        result += coefficient[:, :, None] * residual[:, None, :]
    out_offset = (token[:, None, None] * mhc_mult + out_mix[None, :, None]) * hidden_size + hidden[None, None, :]
    tl.store(out_ptr + out_offset, result.to(tl.bfloat16), mask=mask)

class Model(nn.Module):

    def __init__(self):
        super().__init__()
        profile = _KS_BAKED_PROFILE
        if profile['variant'] not in {'tiled_hidden', 'flat_elementwise', 'fp32_input_tiled', 'fused_mix_tiled'}:
            raise ValueError(f"unsupported mhc_post variant: {profile['variant']}")
        self._ks_variant = profile['variant']
        self._ks_config = profile['config']

    def forward(self, x: torch.Tensor, residual: torch.Tensor, post_layer_mix: torch.Tensor, comb_res_mix: torch.Tensor) -> torch.Tensor:
        hidden_size = x.shape[-1]
        mhc_mult = residual.shape[-2]
        if self._ks_variant == 'fp32_input_tiled':
            out = torch.empty_like(residual.contiguous())
            kernel_x = x.float().contiguous()
            kernel_residual = residual.float().contiguous()
            kernel_post = post_layer_mix.contiguous()
            kernel_comb = comb_res_mix.contiguous()
        else:
            out = torch.empty_like(residual)
            kernel_x = x
            kernel_residual = residual
            kernel_post = post_layer_mix
            kernel_comb = comb_res_mix
        if self._ks_variant == 'fused_mix_tiled':
            block_hidden = int(self._ks_config['block_hidden'])
            block_tokens = int(self._ks_config.get('block_tokens', 1))
            block_mixes = int(self._ks_config.get('block_mixes', mhc_mult))
            if block_hidden <= 0 or block_tokens <= 0 or block_mixes <= 0:
                raise ValueError('invalid fused mhc_post tile configuration')
            token_count = x.numel() // hidden_size
            _mhc_post_fused_mix_kernel[triton.cdiv(token_count, block_tokens), triton.cdiv(hidden_size, block_hidden)](kernel_x, kernel_residual, kernel_post, kernel_comb, out, hidden_size, mhc_mult, token_count, BLOCK_H=block_hidden, BLOCK_TOKENS=block_tokens, BLOCK_MIXES=block_mixes, num_warps=int(self._ks_config['num_warps']))
        elif self._ks_variant in {'tiled_hidden', 'fp32_input_tiled'}:
            block_hidden = int(self._ks_config['block_hidden'])
            block_tokens = int(self._ks_config.get('block_tokens', 1))
            if block_hidden <= 0:
                raise ValueError('block_hidden must be positive')
            if block_tokens <= 0:
                raise ValueError('block_tokens must be positive')
            token_count = x.numel() // hidden_size
            _mhc_post_tiled_kernel[triton.cdiv(token_count, block_tokens), mhc_mult, triton.cdiv(hidden_size, block_hidden)](kernel_x, kernel_residual, kernel_post, kernel_comb, out, hidden_size, mhc_mult, token_count, BLOCK_H=block_hidden, BLOCK_TOKENS=block_tokens, num_warps=int(self._ks_config['num_warps']))
        else:
            total = out.numel()
            block = int(self._ks_config['block'])
            _mhc_post_kernel[triton.cdiv(total, block),](x, residual, post_layer_mix, comb_res_mix, out, hidden_size, mhc_mult, total, BLOCK=block, num_warps=int(self._ks_config['num_warps']))
        return out

def get_inputs():
    (n0, n1, hidden_size, mhc_mult) = (2, 4096, 1280, 4)
    x = torch.randn((n0, n1, hidden_size), dtype=torch.bfloat16)
    residual = torch.randn((n0, n1, mhc_mult, hidden_size), dtype=torch.bfloat16)
    post_layer_mix = torch.randn((n0, n1, mhc_mult, 1), dtype=torch.float32)
    comb_res_mix = torch.randn((n0, n1, mhc_mult, mhc_mult), dtype=torch.float32)
    return [x, residual, post_layer_mix, comb_res_mix]

def get_init_inputs():
    return []
