# Generated by tools/build_submission.py; do not edit.
# task_key=10_head_compute_mix_bwd chip_key=metax_c500 builder_version=3
import torch
import torch.nn as nn
import triton
import triton.language as tl
_KS_BAKED_PROFILE = {'variant': 'chunked_deterministic', 'config': {'block_rows': 256, 'num_warps': 4, 'reduce_num_warps': 1}, 'fallback_variants': [{'variant': 'single_block_reduce', 'config': {'num_warps': 8}}], 'schema_version': 1, 'task_key': '10_head_compute_mix_bwd', 'chip_key': 'metax_c500', 'verified': False}

def get_operator_profile(task_key, chip_key=None):
    if task_key != _KS_BAKED_PROFILE['task_key']:
        raise ValueError(f"artifact profile is for {_KS_BAKED_PROFILE['task_key']}, not {task_key}")
    if chip_key is not None and chip_key != _KS_BAKED_PROFILE['chip_key']:
        raise ValueError(f"artifact profile is for {_KS_BAKED_PROFILE['chip_key']}, not {chip_key}")
    return _KS_BAKED_PROFILE

@triton.jit
def _head_mix_bwd_kernel(input_ptr, scale_ptr, base_ptr, grad_out_ptr, grad_input_ptr, grad_scale_parts_ptr, grad_base_ptr, rows: tl.constexpr, mhc_mult: tl.constexpr, BLOCK: tl.constexpr):
    mix = tl.program_id(0)
    row = tl.arange(0, BLOCK)
    valid = row < rows
    offset = row * mhc_mult + mix
    x = tl.load(input_ptr + offset, mask=valid, other=0.0).to(tl.float32)
    scale = tl.load(scale_ptr).to(tl.float32)
    base = tl.load(base_ptr + mix).to(tl.float32)
    grad_out = tl.load(grad_out_ptr + offset, mask=valid, other=0.0).to(tl.float32)
    sigmoid = tl.sigmoid(x * scale + base)
    grad_z = grad_out * sigmoid * (1.0 - sigmoid)
    tl.store(grad_input_ptr + offset, grad_z * scale, mask=valid)
    tl.store(grad_base_ptr + mix, tl.sum(grad_z, axis=0))
    tl.store(grad_scale_parts_ptr + mix, tl.sum(grad_z * x, axis=0))

@triton.jit
def _head_mix_bwd_chunked_kernel(input_ptr, scale_ptr, base_ptr, grad_out_ptr, grad_input_ptr, grad_scale_partial_ptr, grad_base_partial_ptr, rows, mhc_mult: tl.constexpr, BLOCK_ROWS: tl.constexpr):
    mix = tl.program_id(0)
    chunk = tl.program_id(1)
    row = chunk * BLOCK_ROWS + tl.arange(0, BLOCK_ROWS)
    valid = row < rows
    offset = row * mhc_mult + mix
    x = tl.load(input_ptr + offset, mask=valid, other=0.0).to(tl.float32)
    scale = tl.load(scale_ptr).to(tl.float32)
    base = tl.load(base_ptr + mix).to(tl.float32)
    grad_out = tl.load(grad_out_ptr + offset, mask=valid, other=0.0).to(tl.float32)
    sigmoid = tl.sigmoid(x * scale + base)
    grad_z = grad_out * sigmoid * (1.0 - sigmoid)
    tl.store(grad_input_ptr + offset, grad_z * scale, mask=valid)
    partial_offset = chunk * mhc_mult + mix
    tl.store(grad_base_partial_ptr + partial_offset, tl.sum(grad_z, axis=0))
    tl.store(grad_scale_partial_ptr + partial_offset, tl.sum(grad_z * x, axis=0))

@triton.jit
def _reduce_head_mix_parts_kernel(grad_scale_partial_ptr, grad_base_partial_ptr, grad_scale_parts_ptr, grad_base_ptr, num_chunks, mhc_mult: tl.constexpr, BLOCK_CHUNKS: tl.constexpr):
    mix = tl.program_id(0)
    chunk = tl.arange(0, BLOCK_CHUNKS)
    valid = chunk < num_chunks
    offsets = chunk * mhc_mult + mix
    grad_scale = tl.load(grad_scale_partial_ptr + offsets, mask=valid, other=0.0).to(tl.float32)
    grad_base = tl.load(grad_base_partial_ptr + offsets, mask=valid, other=0.0).to(tl.float32)
    tl.store(grad_scale_parts_ptr + mix, tl.sum(grad_scale, axis=0))
    tl.store(grad_base_ptr + mix, tl.sum(grad_base, axis=0))

@triton.jit
def _sum_scale_parts_kernel(parts_ptr, out_ptr, mhc_mult: tl.constexpr, BLOCK_MIXES: tl.constexpr):
    offsets = tl.arange(0, BLOCK_MIXES)
    parts = tl.load(parts_ptr + offsets, mask=offsets < mhc_mult, other=0.0)
    tl.store(out_ptr, tl.sum(parts.to(tl.float32), axis=0))

class Model(nn.Module):

    def __init__(self):
        super().__init__()
        profile = get_operator_profile('10_head_compute_mix_bwd')
        if profile['variant'] not in {'single_block_reduce', 'chunked_deterministic'}:
            raise ValueError(f"unsupported head_compute_mix_bwd variant: {profile['variant']}")
        self._ks_variant = profile['variant']
        self._ks_config = profile['config']

    def forward(self, input_mix: torch.Tensor, mhc_scale: torch.Tensor, mhc_base: torch.Tensor, grad_out: torch.Tensor):
        mhc_mult = input_mix.shape[-1]
        rows = input_mix.numel() // mhc_mult
        grad_input = torch.empty_like(input_mix)
        grad_scale_parts = torch.empty(mhc_mult, device=input_mix.device, dtype=torch.float32)
        grad_base = torch.empty_like(mhc_base)
        if self._ks_variant == 'single_block_reduce':
            block = triton.next_power_of_2(rows)
            _head_mix_bwd_kernel[mhc_mult,](input_mix, mhc_scale, mhc_base, grad_out, grad_input, grad_scale_parts, grad_base, rows, mhc_mult, BLOCK=block, num_warps=int(self._ks_config['num_warps']))
        else:
            block_rows = int(self._ks_config['block_rows'])
            num_chunks = triton.cdiv(rows, block_rows)
            partial_shape = (num_chunks, mhc_mult)
            grad_scale_partial = torch.empty(partial_shape, device=input_mix.device, dtype=torch.float32)
            grad_base_partial = torch.empty_like(grad_scale_partial)
            _head_mix_bwd_chunked_kernel[mhc_mult, num_chunks](input_mix, mhc_scale, mhc_base, grad_out, grad_input, grad_scale_partial, grad_base_partial, rows, mhc_mult, BLOCK_ROWS=block_rows, num_warps=int(self._ks_config['num_warps']))
            block_chunks = triton.next_power_of_2(num_chunks)
            _reduce_head_mix_parts_kernel[mhc_mult,](grad_scale_partial, grad_base_partial, grad_scale_parts, grad_base, num_chunks, mhc_mult, BLOCK_CHUNKS=block_chunks, num_warps=int(self._ks_config['reduce_num_warps']))
        grad_scale = torch.empty_like(mhc_scale)
        _sum_scale_parts_kernel[1,](grad_scale_parts, grad_scale, mhc_mult=mhc_mult, BLOCK_MIXES=triton.next_power_of_2(mhc_mult), num_warps=1)
        return (grad_input, grad_scale, grad_base)

def get_inputs():
    input_mix = torch.randn(2, 1024, 4, dtype=torch.float32)
    mhc_scale = torch.randn(1, dtype=torch.float32)
    mhc_base = torch.randn(4, dtype=torch.float32)
    grad_out = torch.randn(2, 1024, 4, dtype=torch.float32)
    return [input_mix, mhc_scale, mhc_base, grad_out]

def get_init_inputs():
    return []
