# Generated by tools/build_submission.py; do not edit.
# task_key=06_mm_encoder_attention chip_key=cambricon_mlu590_m9d builder_version=4
import torch_mlu
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch
import triton
import triton.language as tl
_KS_BAKED_PROFILE = {'variant': 'tiled_online_softmax', 'config': {'num_warps': 8, 'block_n': 64}, 'schema_version': 1, 'task_key': '06_mm_encoder_attention', 'chip_key': 'cambricon_mlu590_m9d', 'verified': False}
'Shared, conservative Triton kernels used by multiple competition tasks.\n\nThe code intentionally sticks to operations implemented by the major Triton\nforks used by the competition: masked load/store, reductions, exp/erf and\n`tl.dot`.  Backend-specific tuning belongs in per-chip configuration files;\nthe default configurations favor portability and correctness.\n'

@triton.jit
def _linear_kernel(a_ptr, w_ptr, bias_ptr, out_ptr, m_size: tl.constexpr, n_size: tl.constexpr, k_size: tl.constexpr, stride_am: tl.constexpr, stride_ak: tl.constexpr, stride_wn: tl.constexpr, stride_wk: tl.constexpr, stride_om: tl.constexpr, stride_on: tl.constexpr, HAS_BIAS: tl.constexpr, EPILOGUE: tl.constexpr, BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)
    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)
    acc = tl.zeros((BLOCK_M, BLOCK_N), tl.float32)
    for k0 in range(0, k_size, BLOCK_K):
        k = k0 + offs_k
        a = tl.load(a_ptr + offs_m[:, None] * stride_am + k[None, :] * stride_ak, mask=(offs_m[:, None] < m_size) & (k[None, :] < k_size), other=0.0)
        w = tl.load(w_ptr + offs_n[None, :] * stride_wn + k[:, None] * stride_wk, mask=(offs_n[None, :] < n_size) & (k[:, None] < k_size), other=0.0)
        acc += tl.dot(a, w)
    if HAS_BIAS:
        bias = tl.load(bias_ptr + offs_n, mask=offs_n < n_size, other=0.0)
        acc += bias[None, :]
    if EPILOGUE == 1:
        acc = tl.log(1.0 + tl.maximum(acc, 0.0))
    tl.store(out_ptr + offs_m[:, None] * stride_om + offs_n[None, :] * stride_on, acc, mask=(offs_m[:, None] < m_size) & (offs_n[None, :] < n_size))

def triton_linear(x: torch.Tensor, weight: torch.Tensor, bias: torch.Tensor | None, *, log1p_relu: bool=False, config: dict[str, int]) -> torch.Tensor:
    """Compute a 2-D nn.Linear with a portable tiled Triton kernel."""
    if x.ndim != 2 or weight.ndim != 2:
        raise ValueError('triton_linear expects 2-D input and weight')
    m_size, k_size = x.shape
    n_size = weight.shape[0]
    out = torch.empty((m_size, n_size), device=x.device, dtype=x.dtype)
    block_m = int(config['block_m'])
    block_n = int(config['block_n'])
    block_k = int(config['block_k'])
    grid = (triton.cdiv(m_size, block_m), triton.cdiv(n_size, block_n))
    bias_arg = bias if bias is not None else weight
    _linear_kernel[grid](x, weight, bias_arg, out, m_size, n_size, k_size, x.stride(0), x.stride(1), weight.stride(0), weight.stride(1), out.stride(0), out.stride(1), HAS_BIAS=bias is not None, EPILOGUE=1 if log1p_relu else 0, BLOCK_M=block_m, BLOCK_N=block_n, BLOCK_K=block_k, num_warps=int(config['num_warps']))
    return out

@triton.jit
def _gelu_layer_norm_kernel(x_ptr, weight_ptr, bias_ptr, out_ptr, width: tl.constexpr, eps: tl.constexpr, BLOCK: tl.constexpr):
    row = tl.program_id(0)
    cols = tl.arange(0, BLOCK)
    mask = cols < width
    x = tl.load(x_ptr + row * width + cols, mask=mask, other=0.0).to(tl.float32)
    gelu = 0.5 * x * (1.0 + tl.erf(x * 0.7071067811865476))
    mean = tl.sum(tl.where(mask, gelu, 0.0), axis=0) / width
    centered = tl.where(mask, gelu - mean, 0.0)
    variance = tl.sum(centered * centered, axis=0) / width
    norm = centered * tl.rsqrt(variance + eps)
    weight = tl.load(weight_ptr + cols, mask=mask, other=0.0).to(tl.float32)
    bias = tl.load(bias_ptr + cols, mask=mask, other=0.0).to(tl.float32)
    tl.store(out_ptr + row * width + cols, norm * weight + bias, mask=mask)

def gelu_layer_norm(x: torch.Tensor, weight: torch.Tensor, bias: torch.Tensor, eps: float, *, config: dict[str, int]) -> torch.Tensor:
    rows, width = x.shape
    out = torch.empty_like(x)
    block = triton.next_power_of_2(width)
    _gelu_layer_norm_kernel[rows,](x, weight, bias, out, width, eps, BLOCK=block, num_warps=int(config['num_warps_large'] if block >= 2048 else config['num_warps_small']))
    return out

@triton.jit
def _attention_kernel(q_ptr, k_ptr, v_ptr, out_ptr, batch_size: tl.constexpr, q_len: tl.constexpr, kv_len: tl.constexpr, num_heads: tl.constexpr, head_dim: tl.constexpr, scale, stride_qb: tl.constexpr, stride_qs: tl.constexpr, stride_qh: tl.constexpr, stride_qd: tl.constexpr, stride_kb: tl.constexpr, stride_ks: tl.constexpr, stride_kh: tl.constexpr, stride_kd: tl.constexpr, stride_vb: tl.constexpr, stride_vs: tl.constexpr, stride_vh: tl.constexpr, stride_vd: tl.constexpr, stride_ob: tl.constexpr, stride_os: tl.constexpr, stride_oh: tl.constexpr, stride_od: tl.constexpr, CAUSAL: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_D: tl.constexpr):
    q_index = tl.program_id(0)
    head = tl.program_id(1)
    batch = tl.program_id(2)
    d = tl.arange(0, BLOCK_D)
    d_mask = d < head_dim
    q = tl.load(q_ptr + batch * stride_qb + q_index * stride_qs + head * stride_qh + d * stride_qd, mask=d_mask, other=0.0).to(tl.float32)
    running_max = -float('inf')
    running_norm = 0.0
    result = tl.zeros((BLOCK_D,), tl.float32)
    for n_start in range(0, kv_len, BLOCK_N):
        n = n_start + tl.arange(0, BLOCK_N)
        n_mask = n < kv_len
        k = tl.load(k_ptr + batch * stride_kb + n[:, None] * stride_ks + head * stride_kh + d[None, :] * stride_kd, mask=n_mask[:, None] & d_mask[None, :], other=0.0).to(tl.float32)
        scores = tl.sum(k * q[None, :], axis=1) * scale
        valid = n_mask
        if CAUSAL:
            valid = valid & (n <= q_index)
        scores = tl.where(valid, scores, -float('inf'))
        tile_max = tl.max(scores, axis=0)
        next_max = tl.maximum(running_max, tile_max)
        old_scale = tl.exp(running_max - next_max)
        probs = tl.where(valid, tl.exp(scores - next_max), 0.0)
        v = tl.load(v_ptr + batch * stride_vb + n[:, None] * stride_vs + head * stride_vh + d[None, :] * stride_vd, mask=n_mask[:, None] & d_mask[None, :], other=0.0).to(tl.float32)
        result = result * old_scale + tl.sum(probs[:, None] * v, axis=0)
        running_norm = running_norm * old_scale + tl.sum(probs, axis=0)
        running_max = next_max
    result = result / running_norm
    tl.store(out_ptr + batch * stride_ob + q_index * stride_os + head * stride_oh + d * stride_od, result, mask=d_mask)

def triton_attention(query: torch.Tensor, key: torch.Tensor, value: torch.Tensor, *, scale: float, causal: bool, config: dict[str, int]) -> torch.Tensor:
    """Attention for contiguous logical [B, S, H, D] tensors/views."""
    batch_size, q_len, num_heads, head_dim = query.shape
    kv_len = key.shape[1]
    if key.shape[0] != batch_size or value.shape[0] != batch_size:
        raise ValueError('query/key/value batch sizes must match')
    if key.shape != value.shape:
        raise ValueError('key and value shapes must match')
    if key.shape[2] != num_heads or key.shape[3] != head_dim:
        raise ValueError('query/key/value heads and head dimensions must match')
    out = torch.empty_like(query)
    block_n = int(config.get('block_n', 64))
    if block_n <= 0:
        raise ValueError('attention block_n must be positive')
    block_d = triton.next_power_of_2(head_dim)
    _attention_kernel[q_len, num_heads, batch_size](query, key, value, out, batch_size, q_len, kv_len, num_heads, head_dim, scale, query.stride(0), query.stride(1), query.stride(2), query.stride(3), key.stride(0), key.stride(1), key.stride(2), key.stride(3), value.stride(0), value.stride(1), value.stride(2), value.stride(3), out.stride(0), out.stride(1), out.stride(2), out.stride(3), CAUSAL=causal, BLOCK_N=block_n, BLOCK_D=block_d, num_warps=int(config['num_warps']))
    return out

class Model(nn.Module):

    def __init__(self, num_heads: int=8, head_size: int=64, num_kv_heads: int=8):
        super().__init__()
        self.num_heads = num_heads
        self.head_size = head_size
        self.num_kv_heads = num_kv_heads
        self.scale = 1.0 / head_size ** 0.5
        profile = _KS_BAKED_PROFILE
        if profile['variant'] not in {'tiled_online_softmax', 'native_sdpa'}:
            raise ValueError(f"unsupported MMEncoderAttention variant: {profile['variant']}")
        self._ks_attention_config = profile['config']
        self._ks_variant = profile['variant']

    def forward(self, query: torch.Tensor, key: torch.Tensor, value: torch.Tensor):
        batch_size, q_len = query.shape[:2]
        kv_len = key.shape[1]
        q = query.view(batch_size, q_len, self.num_heads, self.head_size)
        k = key.view(batch_size, kv_len, self.num_kv_heads, self.head_size)
        v = value.view(batch_size, kv_len, self.num_kv_heads, self.head_size)
        if self.num_heads != self.num_kv_heads:
            if self.num_heads % self.num_kv_heads != 0:
                raise ValueError('num_heads must be divisible by num_kv_heads for grouped-query attention')
            repeat = self.num_heads // self.num_kv_heads
            k = k[:, :, :, None, :].expand(batch_size, kv_len, self.num_kv_heads, repeat, self.head_size).reshape(batch_size, kv_len, self.num_heads, self.head_size)
            v = v[:, :, :, None, :].expand(batch_size, kv_len, self.num_kv_heads, repeat, self.head_size).reshape(batch_size, kv_len, self.num_heads, self.head_size)
        if self._ks_variant == 'native_sdpa':
            q_native = q.transpose(1, 2)
            k_native = k.transpose(1, 2)
            v_native = v.transpose(1, 2)
            out = F.scaled_dot_product_attention(q_native, k_native, v_native, scale=self.scale)
            return out.transpose(1, 2).reshape(batch_size, q_len, self.num_heads * self.head_size)
        out = triton_attention(q, k, v, scale=self.scale, causal=False, config=self._ks_attention_config)
        return out.reshape(batch_size, q_len, self.num_heads * self.head_size)

def get_inputs():
    batch_size, seq_len, num_heads, head_size, dtype = (2, 83, 8, 64, torch.float16)
    hidden = num_heads * head_size
    query = torch.randn(batch_size, seq_len, hidden, dtype=dtype, device='mlu')
    key = torch.randn(batch_size, seq_len, hidden, dtype=dtype, device='mlu')
    value = torch.randn(batch_size, seq_len, hidden, dtype=dtype, device='mlu')
    return [query, key, value]

def get_init_inputs():
    return [8, 64, 8]
