"""Build a self-contained, chip-profile-baked operator submission file."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from profile_runtime import (  # noqa: E402
    CHIP_KEYS,
    TASK_KEYS,
    get_operator_profile,
    load_chip_profile,
)


BUILDER_VERSION = 1


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def git_commit() -> str:
    completed = subprocess.run(
        ["git", "-c", f"safe.directory={ROOT.as_posix()}", "rev-parse", "HEAD"],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    return completed.stdout.strip() if completed.returncode == 0 else "unknown"


def _split_module(tree: ast.Module) -> tuple[list[ast.stmt], list[ast.stmt]]:
    imports: list[ast.stmt] = []
    body: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module in {"common", "profile_runtime"}:
            continue
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.append(node)
        else:
            body.append(node)
    return imports, body


def _baked_profile_nodes(profile: dict[str, Any]) -> list[ast.stmt]:
    source = (
        f"_KS_BAKED_PROFILE = {profile!r}\n\n"
        "def get_operator_profile(task_key, chip_key=None):\n"
        "    if task_key != _KS_BAKED_PROFILE['task_key']:\n"
        "        raise ValueError(f'artifact profile is for {_KS_BAKED_PROFILE[\"task_key\"]}, not {task_key}')\n"
        "    if chip_key is not None and chip_key != _KS_BAKED_PROFILE['chip_key']:\n"
        "        raise ValueError(f'artifact profile is for {_KS_BAKED_PROFILE[\"chip_key\"]}, not {chip_key}')\n"
        "    return _KS_BAKED_PROFILE\n"
    )
    return ast.parse(source).body


def _uses_common(tree: ast.Module) -> bool:
    return any(
        isinstance(node, ast.ImportFrom) and node.module == "common" for node in tree.body
    )


def build_submission(
    task_key: str,
    chip_key: str,
    output_path: Path,
    *,
    manifest_path: Path | None = None,
) -> dict[str, Any]:
    if task_key not in TASK_KEYS:
        raise ValueError(f"unknown task_key: {task_key}")
    if chip_key not in CHIP_KEYS:
        raise ValueError(f"unknown chip_key: {chip_key}")

    task_path = ROOT / "triton_kernels" / f"{task_key}.py"
    common_path = ROOT / "triton_kernels" / "common.py"
    profile_path = ROOT / "profiles" / "operators" / f"{task_key}.json"
    chip_path = ROOT / "profiles" / "chips" / f"{chip_key}.json"
    task_tree = ast.parse(task_path.read_text(encoding="utf-8"), filename=str(task_path))
    task_imports, task_body = _split_module(task_tree)

    common_imports: list[ast.stmt] = []
    common_body: list[ast.stmt] = []
    include_common = _uses_common(task_tree)
    if include_common:
        common_tree = ast.parse(
            common_path.read_text(encoding="utf-8"), filename=str(common_path)
        )
        common_imports, common_body = _split_module(common_tree)

    chip_profile = load_chip_profile(chip_key)
    profile = get_operator_profile(task_key, chip_key)
    module = ast.Module(
        body=[
            *task_imports,
            *common_imports,
            *_baked_profile_nodes(profile),
            *common_body,
            *task_body,
        ],
        type_ignores=[],
    )
    ast.fix_missing_locations(module)
    generated = ast.unparse(module) + "\n"
    header = (
        "# Generated by tools/build_submission.py; do not edit.\n"
        f"# task_key={task_key} chip_key={chip_key} builder_version={BUILDER_VERSION}\n"
    )
    payload = (header + generated).encode("utf-8")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(payload)

    manifest: dict[str, Any] = {
        "schema_version": 1,
        "builder_version": BUILDER_VERSION,
        "task_key": task_key,
        "chip_key": chip_key,
        "source_commit": git_commit(),
        "artifact": str(output_path),
        "artifact_sha256": sha256_bytes(payload),
        "sources": {
            task_path.relative_to(ROOT).as_posix(): sha256_file(task_path),
            profile_path.relative_to(ROOT).as_posix(): sha256_file(profile_path),
            chip_path.relative_to(ROOT).as_posix(): sha256_file(chip_path),
        },
        "profile": profile,
        "chip_profile": chip_profile,
    }
    if include_common:
        manifest["sources"][common_path.relative_to(ROOT).as_posix()] = sha256_file(
            common_path
        )
    manifest_path = manifest_path or output_path.with_suffix(".manifest.json")
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", choices=TASK_KEYS)
    parser.add_argument("--chip", choices=CHIP_KEYS)
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--output-root", type=Path, default=ROOT / "artifacts")
    args = parser.parse_args()
    if args.all == bool(args.task or args.chip):
        raise SystemExit("choose either --all or both --task and --chip")
    if not args.all and (not args.task or not args.chip):
        raise SystemExit("--task and --chip are required together")

    pairs = (
        [(task, chip) for chip in CHIP_KEYS for task in TASK_KEYS]
        if args.all
        else [(args.task, args.chip)]
    )
    for task_key, chip_key in pairs:
        output = args.output_root / chip_key / f"{task_key}.py"
        build_submission(task_key, chip_key, output)
        print(f"BUILT {chip_key}/{task_key}")


if __name__ == "__main__":
    main()
